[compat]
	twilightforest = true
	tconstruct = true
	quark = true
	naturalist = true
	mowziesmobs = true
	irons_spellbooks = true
	immersiveengineering = true
	iceandfire = true
	epicfight = true
	create = true
	botania = true
	biomeswevegone = true
	biomesoplenty = true
	artifacts = true
	ars_nouveau = true
	alexsmobs = true
	alexscaves = true
	aether = true
	ae2 = true
	ad_astra = true
